config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'dogs', to: 'dogs#index', as: 'dogs' #index dogs
  get 'dogs/new', to: 'dogs#new', as: 'new_dog' #new
  get 'dogs/:id', to: 'dogs#show', as: 'dog' #show
  get 'dogs/:id/edit', to: 'dogs#edit', as: 'edit_dog' #edit
  post 'dogs', to: 'dogs#create' #create
  patch 'dogs/:id', to: 'dogs#update' #update
  delete 'dogs/:id', to: 'dogs#destroy', as: 'destroy_dog' #destroy

  match '/users/login',      to: 'users#login',           via: 'get'
  match '/users/login',      to: 'users#authorize',        via: 'post'

  get '/users/test', to: 'users#test', as: 'user_test' #New
  post '/users/build', to: 'users#build', as: 'build_user' #Create

  patch '/users/build/:id', to: 'users#change', as: 'change_user' #update

  resources :users do

    get 'define', on: :member #Edit

  end

  resources :numbers
  get 'home/index', as: 'home'
  get 'home/results'

  put 'home/index', to: 'home#comapre', as: 'compare_number'

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :user
end

app/models/number.rb
class Number < ActiveRecord::Base

  def self.compare_numbers (number1, number2)
    if number1 == number2
      return true
    else
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :dogs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  def index
    @dogs = Dog.all
  end

  def show
    #Add to handle JS Request
    respond_to do |format|
        format.html # show.html.erb
        format.js # show.js.erb
    end
  end

  def new
    @dog = Dog.new
  end

  def edit
    respond_to do |format|
        format.html # edit.html.erb
        format.js # edit.js.erb //remote: true
    end
  end

  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully create.' }
        #format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        #format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    #@dog = Dog.find(params[:id]) same as before_action :set_dog, only: [:show, :edit]

    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        #format.json { render :show, status: :ok, location: @dog }
        #format.js { render :index}
      else
        format.html { render :edit }
        #format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      #format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :breed, :user_id)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end

  def compare

  end


end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController
  before_action :set_number, only: [:show, :edit, :update, :destroy]

  # GET /numbers
  # GET /numbers.json
  def index
    @numbers = Number.all
  end

  # GET /numbers/1
  # GET /numbers/1.json
  def show
    @random_number = 1 + rand(10)
    @result = Number.compare_numbers(@number.input, @random_number)
  end

  # GET /numbers/new
  def new
    @number = Number.new
  end


  # POST /numbers
  # POST /numbers.json
  def create
    @number = Number.new(number_params)
    respond_to do |format|
      if @number.save
        format.html { redirect_to @number}
      else
        format.html { render :new }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_number
      @number = Number.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def number_params
      params.require(:number).permit(:input)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :change]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def login


  end

  def authorize
    username = params[:username]
    password = params[:password]

    if user = User.where("userame = ?", params[:userame])
      redirect_to users_url, notice: 'Username Found'
    else
      redirect_to users_url, notice: 'Username Incorrect'
    end

  end

  def test
    @new_user = User.new
  end

  def build
    #@user = User.find(params[:id])
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully built.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end

  def change
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully changed.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/home_helper.rb
module HomeHelper

  

end

app/helpers/numbers_helper.rb
module NumbersHelper


  def compare_numbers (number1, number2)
    if number1 == number2
      return true
    else
      return false
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dogs/_dog_form.html.erb
<%= form_for(@dog) do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.order('username ASC').all, :id, :username %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn"%>
  </div>
<% end %>

app/views/dogs/_dog_show.html.erb
<p>
  <strong>Name:</strong>
  <%= dog.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= dog.breed %>
</p>

app/views/dogs/edit.html.erb
<h1>Edit Dog</h1>

<%= render 'dog_form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/edit.js.erb
$('#dog').hide().fadeIn('slow');
//$('#user').hide().animate({backgroundColor: '#FF0000'}, 'slow')
//escape_javascript(render 'dog_show', :dog => @dog) // allows access to erb
$("#dog").html("<%= escape_javascript(render 'dog_form') %>");

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dogs</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Dog Name</th>
      <th>Breed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <th scope="row"><%= dog.name %></th>
        <td><%= dog.breed %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%#= link_to 'Destroy', destroy_dog_path(dog.id), data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Display Via JS', dog_path(dog), remote: true %></td>
        <td><%= link_to 'Edit Via JS', edit_dog_path(dog), remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--Rendered Dog Info Via JS: Refer to assests dog CSS for dog tag-->
<div class="column" id="dog">

</div>

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/new.html.erb
<h1>Create New Dog</h1>

<%= render 'dog_form' %>

app/views/dogs/show.html.erb
<h1>Dog</h1>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @dog.breed %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/show.js.erb
$('#dog').hide().fadeIn('slow');
//$('#user').hide().animate({backgroundColor: '#FF0000'}, 'slow')
//escape_javascript(render 'dog_show', :dog => @dog) // allows access to erb
$("#dog").html("<%= escape_javascript(render 'dog_show', :dog => @dog) %>");

app/views/home/_answer.html.erb
<% if result == true %>
<p>Numbers are the same.</p>
<% else %>
<p>Numbers are not the same.</p>
<% end %>

app/views/home/index.html.erb
<h1>Random Number Game</h1>
<p>Please guess a number between 1 and 10:</p>

<p> Number 1: <%= @number1%> </p>
<p> Number 2: <%= @number2%> </p>

<p>
<%= form_tag(compare_number_path) do |f|%>
<%#= f.label :numberID %>:
<%#= f.text_field :numberID %><br />
<%#= f.submit %>
<% end %>
</p>

<%= render 'answer', :result => @result %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
<div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>WEBSITE TITLE</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="Description" lang="en" content="ADD SITE DESCRIPTION">
	<meta name="author" content="Kyle Hasty">
	<meta name="robots" content="index, follow">


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
      <div class="messages"><%= render 'layouts/messages' %></div>
			<div class="header">
				<h1 class="header-heading">MY SITE NAME</h1>
			</div>
			<div class="nav-bar">
				<ul class="nav">
          <li><a><%= link_to 'Index', root_path %></a></li>
					<li><a><%= link_to 'Home', home_path %></a></li>
					<li><a><%= link_to 'Users', users_path %></a></li>
					<li><a><%= link_to 'Numbers', numbers_path %></a></li>
          <li><a><%= link_to 'Dogs', dogs_path %></a></li>
				</ul>
			</div>
			<div class="content">

        <!--Rendered Content -->
        <%= yield %>

			</div>
			<div class="footer">
				&copy; Copyright 2016
			</div>
		</div>



</body>
</html>

app/views/numbers/_form.html.erb
<%= form_for(@number) do |f| %>
  <% if @number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@number.errors.count, "error") %> prohibited this number from being saved:</h2>

      <ul>
      <% @number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :input %><br>
    <%= f.number_field :input %>
  </div>
  <div class="actions">
    <%= f.submit "Play Game" %>
  </div>
<% end %>

app/views/numbers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guess a Number between 1 and 10</h1>

<br>

<%= link_to 'New Number', new_number_path %>

app/views/numbers/new.html.erb
<h1>Guess a Number between 1 and 10</h1>
<h2>Submit Number</h2>

<%= render 'form' %>

<%= link_to 'Back', numbers_path %>

app/views/numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numbers Game Results:</strong>
  <p>Your Number: <%= @number.input %></p>
  <p>Our Number:  <%= @random_number %></p>

  <% if @result == true %>
    <p> You Win! </p>
  <% else %>
    <p> Sorry you lose </p>
  <% end %>

  <%= link_to 'Play Again?', new_number_path %>
</p>

app/views/users/_form.html.erb
<p>User:  <%= @user.id %> </p>


<%#= form_for @user, url: change_user_path, html: { method: :patch } do |f| %>
<%= form_for (@user)  do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_login_form.html.erb
<%= form_tag({controller: "users", action: "authorize"}, method: "post") do %>
    <p><%= label_tag(:username, "Username:") %></p>
    <p><%= text_field_tag(:username) %></p>
    <p><%= label_tag(:password, "Password:") %></p>
    <p><%= text_field_tag(:password) %></p>
    <p><%= submit_tag("Submit") %></p>
<% end %>

app/views/users/_test_form.html.erb
<%= form_for @new_user, url: build_user_path, html: { method: :post } do |f| %>


  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<h1>Login</h1>

<%= render 'login_form' %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/test.html.erb
<h1>Test</h1>

<%= render 'test_form' %>

app/views/welcome/index.html.erb
<div class="main">

  <h1>Page title</h1>
  <hr>

  <!-- Heading levels -->
  <h1>Heading level 1</h1>
  <h2>Heading level 2</h2>
  <h3>Heading level 3</h3>
  <h4>Heading level 4</h4>
  <h5>Heading level 5</h5>
  <h6>Heading level 6</h6>
  <hr>

  <!-- Paragraphs -->
  <h3>Paragraphs</h3>
  <p>Ut wisi enim ad minim veniam, <a href="#">quis nostrud exerci tation ullamcorper</a> suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
  <p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
  <hr>

  <!-- Responsive images -->
  <h3>Responsive images</h3>
  <p>For images to be responsive (so that they will rescale to suit the width of the parent, use the <code>.img-responsive</code> class.</p>
  <p><img class="img-responsive" src="http://placehold.it/800x350" alt=""></p>

  <!-- Lists -->
  <h3>Unordered list</h3>
  <p>Unordered lists are used to markup lists where list items do not require numbering.</p>
  <ul>
    <li>Ut wisi enim ad minim veniam</li>
    <li>Quis nostrud exerci tation</li>
    <li>Lamcorper suscipit lobortis nis</li>
    <li>Ut aliquip ex ea commodo consequat</li>
    <li>Duis autem vel eum iriure dolor</li>
  </ul>
  <hr>

  <h3>Ordered list</h3>
  <p>Ordered lists are used to markup lists where list items require numbering.</p>
  <ol>
    <li>Hendrerit in vulputate velit esse</li>
    <li>Olestie consequat</li>
    <li>Vel illum dolore eu feugiat</li>
    <li>Nulla facilisis at vero eros</li>
    <li>Accumsan et iusto odio</li>
  </ol>
  <hr>

  <h3>Unstyled list</h3>
  <p>You can make the list unstyled using the <code>list-unstyled</code> class.</p>
  <ul class="list-unstyled">
    <li>Ut wisi enim ad minim veniam</li>
    <li>Quis nostrud exerci tation</li>
    <li>Lamcorper suscipit lobortis nis</li>
    <li>Ut aliquip ex ea commodo consequat</li>
    <li>Duis autem vel eum iriure dolor</li>
  </ul>
  <hr>

  <h3>Inline list</h3>
  <p>You can make the list display inline using the <code>list-inline</code> class.</p>
  <ul class="list-inline">
    <li>One</li>
    <li>Two</li>
    <li>Three</li>
    <li>Four</li>
  </ul>
  <hr>

  <!-- Blockquotes -->
  <h3>Blockquotes</h3>
  <p>The blockquote element is used to markup long quotations. Ideally, content inside should be wrapped in paragraph elements.</p>
  <blockquote>
    <p>The real names of our people were destroyed during slavery. The last name of my forefathers was taken from them when they were brought to America and made slaves, and then the name of the slave master was given, which we refuse, we reject that name today and refuse it. I never acknowledge it whatsoever.</p>
    <footer><a href="http://en.wikipedia.org/wiki/Malcolm_X">Malcolm X</a></footer>
  </blockquote>
  <hr>

  <h3>Buttons</h3>
  <p>You can apply the <code>btn</code> class to any element that requires a button style.</p>
  <p><a href="#" class="btn">Submit</a></p>
  <hr>

  <!-- Tables -->
  <h3>Tables</h3>
  <p>Tables should be given the class of <code>table</code>.</p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Username</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td>Mark</td>
        <td>Otto</td>
        <td>@mdo</td>
      </tr>
      <tr>
        <th scope="row">2</th>
        <td>Jacob</td>
        <td>Thornton</td>
        <td>@fat</td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td>Larry</td>
        <td>the Bird</td>
        <td>@twitter</td>
      </tr>
    </tbody>
  </table>

</div>